"""add_vibesmith_persona_and_dynamic_state_tables

Revision ID: 947fb5f9abf0
Revises: c31a068a8668
Create Date: 2026-05-06 01:50:20.918667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947fb5f9abf0'
down_revision: Union[str, None] = 'c31a068a8668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_cards',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('age', sa.Text(), nullable=False),
    sa.Column('gender', sa.Text(), nullable=False),
    sa.Column('occupation', sa.Text(), nullable=False),
    sa.Column('realism_level', sa.Text(), nullable=False),
    sa.Column('core_tension', sa.Text(), nullable=False),
    sa.Column('persona_json', sa.Text(), nullable=False),
    sa.Column('md_file_path', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dynamic_states',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('state_blob', sa.LargeBinary(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['persona_cards.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dynamic_states_character', 'dynamic_states', ['character_id'], unique=False)
    op.create_index('ix_dynamic_states_session', 'dynamic_states', ['session_id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('dynamic_state_id', sa.Text(), nullable=False),
    sa.Column('trigger_type', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('emotional_impact', sa.Text(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dynamic_state_id'], ['dynamic_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memories_state', 'memories', ['dynamic_state_id'], unique=False)
    op.create_index('ix_memories_trigger', 'memories', ['trigger_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memories_trigger', table_name='memories')
    op.drop_index('ix_memories_state', table_name='memories')
    op.drop_table('memories')
    op.drop_index('ix_dynamic_states_session', table_name='dynamic_states')
    op.drop_index('ix_dynamic_states_character', table_name='dynamic_states')
    op.drop_table('dynamic_states')
    op.drop_table('persona_cards')
    # ### end Alembic commands ###
