"""Add 8 fields to ai_personas

Revision ID: c31a068a8668
Revises: 792a1c255924
Create Date: 2026-05-01 02:50:16.971073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31a068a8668'
down_revision: Union[str, None] = '792a1c255924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_personas', sa.Column('age', sa.Text(), server_default="", nullable=False))
    op.add_column('ai_personas', sa.Column('gender', sa.Text(), server_default="", nullable=False))
    op.add_column('ai_personas', sa.Column('appearance', sa.Text(), server_default="", nullable=False))
    op.add_column('ai_personas', sa.Column('backstory', sa.Text(), server_default="", nullable=False))
    op.add_column('ai_personas', sa.Column('relationships', sa.Text(), server_default="", nullable=False))
    op.add_column('ai_personas', sa.Column('skills', sa.Text(), server_default="", nullable=False))
    op.add_column('ai_personas', sa.Column('interests', sa.Text(), server_default="", nullable=False))
    op.add_column('ai_personas', sa.Column('weaknesses', sa.Text(), server_default="", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_personas', 'weaknesses')
    op.drop_column('ai_personas', 'interests')
    op.drop_column('ai_personas', 'skills')
    op.drop_column('ai_personas', 'relationships')
    op.drop_column('ai_personas', 'backstory')
    op.drop_column('ai_personas', 'appearance')
    op.drop_column('ai_personas', 'gender')
    op.drop_column('ai_personas', 'age')
    # ### end Alembic commands ###
