"""initial_schema

Revision ID: 792a1c255924
Revises: 
Create Date: 2026-04-29 07:07:28.804179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792a1c255924'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_personas',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role_name', sa.Text(), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('speaking_style', sa.Text(), nullable=False),
    sa.Column('goals', sa.Text(), nullable=False),
    sa.Column('restrictions', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lorebooks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('provider_profiles',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('provider_kind', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('secret_ref', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_personas',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('speaking_style', sa.Text(), nullable=False),
    sa.Column('boundaries', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('worldbooks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lore_entries',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('lorebook_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('activation_keys_json', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lorebook_id'], ['lorebooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_cache',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('provider_profile_id', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('context_window_tokens', sa.Integer(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('supported_parameters_json', sa.Text(), nullable=False),
    sa.Column('supports_streaming', sa.Integer(), nullable=False),
    sa.Column('supports_system_prompt', sa.Integer(), nullable=False),
    sa.Column('supports_json_mode', sa.Integer(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['provider_profile_id'], ['provider_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_cache_provider_model', 'model_cache', ['provider_profile_id', 'model_id'], unique=True)
    op.create_table('model_profiles',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('provider_profile_id', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['provider_profile_id'], ['provider_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('world_entries',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('worldbook_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['worldbook_id'], ['worldbooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_profiles',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('model_profile_id', sa.Text(), nullable=False),
    sa.Column('ai_persona_ids_json', sa.Text(), nullable=False),
    sa.Column('lorebook_ids_json', sa.Text(), nullable=False),
    sa.Column('worldbook_ids_json', sa.Text(), nullable=False),
    sa.Column('prompt_order_json', sa.Text(), nullable=False),
    sa.Column('system_base', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['model_profile_id'], ['model_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('chat_profile_id', sa.Text(), nullable=False),
    sa.Column('user_persona_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chat_profile_id'], ['chat_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_persona_id'], ['user_personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('prompt_snapshot_json', sa.Text(), nullable=True),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    op.drop_table('chat_sessions')
    op.drop_table('chat_profiles')
    op.drop_table('world_entries')
    op.drop_table('model_profiles')
    op.drop_index('ix_model_cache_provider_model', table_name='model_cache')
    op.drop_table('model_cache')
    op.drop_table('lore_entries')
    op.drop_table('worldbooks')
    op.drop_table('user_personas')
    op.drop_table('provider_profiles')
    op.drop_table('lorebooks')
    op.drop_table('ai_personas')
    # ### end Alembic commands ###
